# Generated by Django 5.2.17 on 2026-09-28 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_audit_log_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target', '-created_at'], name='accounts_audit_target_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='accounts_audit_created'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['USER_CREATED', 'USER_UPDATED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'ROLES_CHANGED'])), name='accounts_auditlog_action_valid'),
        ),
    ]
