# Generated by Django 5.2.17 on 2026-09-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_audit_log_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
