# Generated by Django 5.2.17 on 2026-09-29 23:34

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}-[12]$', 'Usa el formato AAAA-S, con semestre 1 o 2 (por ejemplo 2026-1).')], verbose_name='código')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^\\d{4}-[12]$')), name='academics_term_code_format'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academics_term_ends_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]*$', 'Usa solo letras y dígitos, empezando por una letra (por ejemplo MAT).')], verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='academics_department_name_ci_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z][A-Z0-9]*$')), name='academics_department_code_format')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+(-[A-Z0-9]+)*$', 'Usa solo letras, dígitos y guiones (por ejemplo MAT-101).')], verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('credits', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='créditos')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='horas comprometidas')),
                ('monitor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='monitor_assignments', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitor_assignments', to='academics.academicterm')),
                ('subject', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='monitor_assignments', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name', 'monitor__email'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Usa solo letras y dígitos (por ejemplo 1 o A).')], verbose_name='grupo')),
                ('teacher', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.academicterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name', 'group'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='academics_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gt', 0)), name='academics_subject_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9]+(-[A-Z0-9]+)*$')), name='academics_subject_code_format'),
        ),
        migrations.AddIndex(
            model_name='monitorassignment',
            index=models.Index(fields=['subject', 'term'], name='academics_assign_subject_term'),
        ),
        migrations.AddConstraint(
            model_name='monitorassignment',
            constraint=models.UniqueConstraint(fields=('monitor', 'subject', 'term'), name='academics_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='monitorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('committed_hours__gt', 0)), name='academics_assignment_hours_positive'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term', 'teacher'], name='academics_course_term_teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'term'], name='academics_course_teacher_term'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'term', 'group'), name='academics_course_unique'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('group__regex', '^[A-Z0-9]+$')), name='academics_course_group_format'),
        ),
    ]
