/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Hands out the CSRF token the frontend echoes in X-CSRFToken (ADR-007).
         *
         *     The token travels in the body because the frontend may run on another host, where it
         *     cannot read the API's cookies; the csrftoken cookie itself stays HttpOnly.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Issues the access and refresh tokens as HttpOnly cookies (ADR-007). */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Revokes the refresh token and clears the token cookies.
         *
         *     No authentication: an expired access cookie must not prevent revoking the refresh token.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Issues a new access cookie from the refresh cookie, even if the access token expired. */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public self-registration with an institutional email (HU-01). */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Headline numbers of the catalog for one term (the current one by default). */
        get: operations["catalog_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Courses of one term (the current one by default); administrators only (RF-024). */
        get: operations["courses_list"];
        put?: never;
        /** @description Courses of one term (the current one by default); administrators only (RF-024). */
        post: operations["courses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrators read a course and change its group or teacher. PUT is not offered. */
        get: operations["courses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Administrators read a course and change its group or teacher. PUT is not offered. */
        patch: operations["courses_partial_update"];
        trace?: never;
    };
    "/api/v1/courses/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The requesting teacher's own courses and their monitors (T-02.8, RN-009.1). */
        get: operations["courses_mine_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Everyone reads active departments; administrators also see inactive ones and write. */
        get: operations["departments_list"];
        put?: never;
        /** @description Everyone reads active departments; administrators also see inactive ones and write. */
        post: operations["departments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read one department; administrators edit it. PUT is not offered. */
        get: operations["departments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read one department; administrators edit it. PUT is not offered. */
        patch: operations["departments_partial_update"];
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reports service liveness and database connectivity. No authentication required. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitor-assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Monitor assignments of one term; administrators authorize monitors (RF-023). */
        get: operations["monitor_assignments_list"];
        put?: never;
        /** @description Monitor assignments of one term; administrators authorize monitors (RF-023). */
        post: operations["monitor_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitor-assignments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Administrators withdraw a monitor's authorization. */
        delete: operations["monitor_assignments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitor-assignments/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The requesting monitor's own assignments and their subjects' teachers (RN-009.1). */
        get: operations["monitor_assignments_mine_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The subject catalog with its filters; administrators create subjects (RF-022). */
        get: operations["subjects_list"];
        put?: never;
        /** @description The subject catalog with its filters; administrators create subjects (RF-022). */
        post: operations["subjects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read one subject; administrators edit or deactivate it (T-02.7). PUT is not offered. */
        get: operations["subjects_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read one subject; administrators edit or deactivate it (T-02.7). PUT is not offered. */
        patch: operations["subjects_partial_update"];
        trace?: never;
    };
    "/api/v1/terms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every authenticated user lists terms (term switcher); administrators create them. */
        get: operations["terms_list"];
        put?: never;
        /** @description Every authenticated user lists terms (term switcher); administrators create them. */
        post: operations["terms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terms/current/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The term containing today; else the latest past one; else the nearest upcoming one. */
        get: operations["terms_current_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrators list, search and filter accounts and create new ones (RF-020, RF-021). */
        get: operations["users_list"];
        put?: never;
        /** @description Administrators list, search and filter accounts and create new ones (RF-020, RF-021). */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrators read and edit one account; PUT is not offered. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Administrators read and edit one account; PUT is not offered. */
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reports the impact first; deactivates only with confirm=true (CA-HU11-2, CA-HU11-3). */
        post: operations["users_deactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Replaces the roles of one account (RF-021). */
        post: operations["users_roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every account matching the list filters as an .xlsx download, without pagination. */
        get: operations["users_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated user's own identity and roles (CA-HU01-5). */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Headline numbers and the latest audit entries for the admin dashboard. */
        get: operations["users_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcademicTerm: {
            readonly id: number;
            /** @description Formato AAAA-S, por ejemplo 2026-1. */
            code: string;
            /**
             * Fecha de inicio
             * Format: date
             */
            start_date: string;
            /**
             * Fecha de fin
             * Format: date
             */
            end_date: string;
        };
        /**
         * @description * `USER_CREATED` - Usuario creado
         *     * `USER_UPDATED` - Usuario editado
         *     * `USER_ACTIVATED` - Usuario activado
         *     * `USER_DEACTIVATED` - Usuario desactivado
         *     * `ROLES_CHANGED` - Roles modificados
         * @enum {string}
         */
        ActionEnum: "USER_CREATED" | "USER_UPDATED" | "USER_ACTIVATED" | "USER_DEACTIVATED" | "ROLES_CHANGED";
        AdminUser: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Correo
             * Format: email
             */
            readonly email: string;
            /** Nombre */
            readonly first_name: string;
            /** Apellido */
            readonly last_name: string;
            readonly roles: components["schemas"]["RolesEnum"][];
            readonly is_active: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
        /** @description A monitor of one of the teacher's courses; `id` is the monitor's user id. */
        AssignedMonitor: {
            /** Format: uuid */
            id: string;
            readonly full_name: string;
            /** Format: email */
            email: string;
            committed_hours: number;
        };
        AuditEntry: {
            id: number;
            action: components["schemas"]["ActionEnum"];
            /** Format: date-time */
            created_at: string;
            actor: components["schemas"]["UserReference"] | null;
            target: components["schemas"]["UserReference"] | null;
        };
        CatalogSummary: {
            /** @description Código del período resumido. */
            term: string | null;
            subjects_active: number;
            departments_active: number;
            courses: number;
            courses_without_teacher: number;
            courses_without_monitor: number;
            monitor_assignments: number;
            committed_hours_total: number;
        };
        Course: {
            readonly id: number;
            readonly subject: components["schemas"]["SubjectSummary"];
            /** Código */
            readonly term: string;
            /** Grupo */
            readonly group: string;
            readonly teacher: components["schemas"]["UserReference"] | null;
            /** @description Monitores asignados a la asignatura en el período del curso. */
            readonly monitor_count: number;
        };
        CourseCreate: {
            subject: number;
            /** Código */
            term: string;
            group: string;
            /**
             * Format: uuid
             * @description Id de un usuario Docente.
             */
            teacher?: string | null;
        };
        CsrfToken: {
            csrfToken: string;
        };
        DeactivationImpact: {
            future_reservations: number;
        };
        DeactivationRequest: {
            /** @default false */
            confirm: boolean;
        };
        DeactivationResult: {
            deactivated: boolean;
            impact: components["schemas"]["DeactivationImpact"];
            user: components["schemas"]["AdminUser"];
        };
        Department: {
            readonly id: number;
            code: string;
            name: string;
            is_active?: boolean;
        };
        DepartmentReference: {
            readonly id: number;
            /** Código */
            readonly code: string;
            /** Nombre */
            readonly name: string;
        };
        Health: {
            status: string;
            database: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        MonitorAssignment: {
            readonly id: number;
            readonly monitor: components["schemas"]["UserReference"];
            readonly subject: components["schemas"]["SubjectReference"];
            /** Código */
            readonly term: string;
            /** Horas comprometidas */
            readonly committed_hours: number;
        };
        MonitorAssignmentCreate: {
            /**
             * Format: uuid
             * @description Id de un usuario Monitor.
             */
            monitor: string;
            subject: number;
            /** Código */
            term: string;
            committed_hours: number;
        };
        MonitorOwnAssignment: {
            readonly id: number;
            readonly subject: components["schemas"]["SubjectSummary"];
            /** Código */
            readonly term: string;
            /** Horas comprometidas */
            readonly committed_hours: number;
            readonly teachers: components["schemas"]["SubjectTeacher"][];
        };
        PaginatedAcademicTermList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AcademicTerm"][];
        };
        PaginatedAdminUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminUser"][];
        };
        PaginatedCourseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Course"][];
        };
        PaginatedDepartmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Department"][];
        };
        PaginatedMonitorAssignmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MonitorAssignment"][];
        };
        PaginatedMonitorOwnAssignmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MonitorOwnAssignment"][];
        };
        PaginatedSubjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Subject"][];
        };
        PaginatedTeacherCourseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeacherCourse"][];
        };
        PatchedCourseUpdate: {
            group?: string;
            /**
             * Format: uuid
             * @description Id de un usuario Docente.
             */
            teacher?: string | null;
        };
        PatchedDepartment: {
            readonly id?: number;
            code?: string;
            name?: string;
            is_active?: boolean;
        };
        PatchedSubjectWrite: {
            code?: string;
            /** Nombre */
            name?: string;
            /** Créditos */
            credits?: number;
            department?: number;
            is_active?: boolean;
        };
        PatchedUserUpdate: {
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            is_active?: boolean;
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
        };
        RoleAssignment: {
            roles: components["schemas"]["RolesEnum"][];
        };
        RoleCounts: {
            STUDENT: number;
            MONITOR: number;
            TEACHER: number;
            ADMIN: number;
        };
        /**
         * @description * `STUDENT` - Estudiante
         *     * `MONITOR` - Monitor
         *     * `TEACHER` - Docente
         *     * `ADMIN` - Administrador
         * @enum {string}
         */
        RolesEnum: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
        Subject: {
            readonly id: number;
            /** Código */
            readonly code: string;
            /** Nombre */
            readonly name: string;
            /** Créditos */
            readonly credits: number;
            readonly is_active: boolean;
            readonly department: components["schemas"]["DepartmentReference"];
            /** @description Asignaciones de monitoría de la asignatura en el período. */
            readonly monitor_count: number;
        };
        SubjectReference: {
            readonly id: number;
            /** Código */
            readonly code: string;
            /** Nombre */
            readonly name: string;
        };
        SubjectSummary: {
            readonly id: number;
            /** Código */
            readonly code: string;
            /** Nombre */
            readonly name: string;
            /** Créditos */
            readonly credits: number;
            readonly department: components["schemas"]["DepartmentReference"];
        };
        /** @description A teacher of the monitor's subject in the term; `id` is the teacher's user id. */
        SubjectTeacher: {
            /** Format: uuid */
            id: string;
            readonly full_name: string;
            /** Format: email */
            email: string;
            group: string;
        };
        SubjectWrite: {
            code: string;
            /** Nombre */
            name: string;
            /** Créditos */
            credits: number;
            department: number;
            is_active?: boolean;
        };
        TeacherCourse: {
            readonly id: number;
            readonly subject: components["schemas"]["SubjectSummary"];
            /** Código */
            readonly term: string;
            /** Grupo */
            readonly group: string;
            readonly monitors: components["schemas"]["AssignedMonitor"][];
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Correo
             * Format: email
             */
            readonly email: string;
            /** Nombre */
            readonly first_name: string;
            /** Apellido */
            readonly last_name: string;
            readonly roles: components["schemas"]["RolesEnum"][];
        };
        /** @description Same rules as self-registration, but the administrator chooses the roles. */
        UserCreate: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
            roles: components["schemas"]["RolesEnum"][];
        };
        UserReference: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            readonly full_name: string;
        };
        UserSummary: {
            total: number;
            active: number;
            inactive: number;
            joined_last_30_days: number;
            by_role: components["schemas"]["RoleCounts"];
            recent_activity: components["schemas"]["AuditEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    catalog_summary_retrieve: {
        parameters: {
            query?: {
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSummary"];
                };
            };
        };
    };
    courses_list: {
        parameters: {
            query?: {
                /** @description Id o código del departamento. */
                department?: string;
                /**
                 * @description * `code` - code
                 *     * `name` - name
                 *     * `-monitor_count` - -monitor_count
                 */
                ordering?: "code" | "name" | "-monitor_count";
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Busca en código y nombre de la asignatura y en nombre y correo del docente. */
                search?: string;
                /** @description Código del período; por defecto, el actual. */
                term?: string;
                without_monitors?: boolean;
                without_teacher?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCourseList"];
                };
            };
        };
    };
    courses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseCreate"];
                "multipart/form-data": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    courses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCourseUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCourseUpdate"];
                "multipart/form-data": components["schemas"]["PatchedCourseUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    courses_mine_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeacherCourseList"];
                };
            };
        };
    };
    departments_list: {
        parameters: {
            query?: {
                /** @description Solo administradores. */
                active?: boolean;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDepartmentList"];
                };
            };
        };
    };
    departments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Department"];
                "application/x-www-form-urlencoded": components["schemas"]["Department"];
                "multipart/form-data": components["schemas"]["Department"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDepartment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDepartment"];
                "multipart/form-data": components["schemas"]["PatchedDepartment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    monitor_assignments_list: {
        parameters: {
            query?: {
                /** @description Id del monitor. */
                monitor?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Busca en nombre y correo del monitor y en código y nombre de la asignatura. */
                search?: string;
                /** @description Id de asignatura. */
                subject?: number;
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMonitorAssignmentList"];
                };
            };
        };
    };
    monitor_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorAssignmentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["MonitorAssignmentCreate"];
                "multipart/form-data": components["schemas"]["MonitorAssignmentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorAssignment"];
                };
            };
        };
    };
    monitor_assignments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monitor_assignments_mine_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMonitorOwnAssignmentList"];
                };
            };
        };
    };
    subjects_list: {
        parameters: {
            query?: {
                /** @description Solo administradores. */
                active?: boolean;
                credits?: number;
                /** @description Id o código del departamento. */
                department?: string;
                has_monitors?: boolean;
                /**
                 * @description * `code` - code
                 *     * `name` - name
                 *     * `-monitor_count` - -monitor_count
                 */
                ordering?: "code" | "name" | "-monitor_count";
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Busca en código y nombre. */
                search?: string;
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectList"];
                };
            };
        };
    };
    subjects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["SubjectWrite"];
                "multipart/form-data": components["schemas"]["SubjectWrite"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subjects_retrieve: {
        parameters: {
            query?: {
                /** @description Código del período; por defecto, el actual. */
                term?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subjects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSubjectWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSubjectWrite"];
                "multipart/form-data": components["schemas"]["PatchedSubjectWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    terms_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAcademicTermList"];
                };
            };
        };
    };
    terms_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicTerm"];
                "application/x-www-form-urlencoded": components["schemas"]["AcademicTerm"];
                "multipart/form-data": components["schemas"]["AcademicTerm"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicTerm"];
                };
            };
        };
    };
    terms_current_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicTerm"];
                };
            };
            /** @description No terms yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /**
                 * @description * `STUDENT` - Estudiante
                 *     * `MONITOR` - Monitor
                 *     * `TEACHER` - Docente
                 *     * `ADMIN` - Administrador
                 */
                role?: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
                /** @description Busca en correo, nombres, apellidos y nombre completo. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreate"];
                "multipart/form-data": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_deactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeactivationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DeactivationRequest"];
                "multipart/form-data": components["schemas"]["DeactivationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeactivationResult"];
                };
            };
        };
    };
    users_roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignment"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleAssignment"];
                "multipart/form-data": components["schemas"]["RoleAssignment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_export_retrieve: {
        parameters: {
            query?: {
                is_active?: boolean;
                /**
                 * @description * `STUDENT` - Estudiante
                 *     * `MONITOR` - Monitor
                 *     * `TEACHER` - Docente
                 *     * `ADMIN` - Administrador
                 */
                role?: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
                /** @description Busca en correo, nombres, apellidos y nombre completo. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excel workbook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
}
