/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Hands out the CSRF token the frontend echoes in X-CSRFToken (ADR-007).
         *
         *     The token travels in the body because the frontend may run on another host, where it
         *     cannot read the API's cookies; the csrftoken cookie itself stays HttpOnly.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Issues the access and refresh tokens as HttpOnly cookies (ADR-007). */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Revokes the refresh token and clears the token cookies.
         *
         *     No authentication: an expired access cookie must not prevent revoking the refresh token.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Issues a new access cookie from the refresh cookie, even if the access token expired. */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public self-registration with an institutional email (HU-01). */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reports service liveness and database connectivity. No authentication required. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrators list, search and filter accounts and create new ones (RF-020, RF-021). */
        get: operations["users_list"];
        put?: never;
        /** @description Administrators list, search and filter accounts and create new ones (RF-020, RF-021). */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrators read and edit one account; PUT is not offered. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Administrators read and edit one account; PUT is not offered. */
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reports the impact first; deactivates only with confirm=true (CA-HU11-2, CA-HU11-3). */
        post: operations["users_deactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Replaces the roles of one account (RF-021). */
        post: operations["users_roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every account matching the list filters as an .xlsx download, without pagination. */
        get: operations["users_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated user's own identity and roles (CA-HU01-5). */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Headline numbers and the latest audit entries for the admin dashboard. */
        get: operations["users_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `USER_CREATED` - Usuario creado
         *     * `USER_UPDATED` - Usuario editado
         *     * `USER_ACTIVATED` - Usuario activado
         *     * `USER_DEACTIVATED` - Usuario desactivado
         *     * `ROLES_CHANGED` - Roles modificados
         * @enum {string}
         */
        ActionEnum: "USER_CREATED" | "USER_UPDATED" | "USER_ACTIVATED" | "USER_DEACTIVATED" | "ROLES_CHANGED";
        AdminUser: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Correo
             * Format: email
             */
            readonly email: string;
            /** Nombre */
            readonly first_name: string;
            /** Apellido */
            readonly last_name: string;
            readonly roles: components["schemas"]["RolesEnum"][];
            readonly is_active: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
        AuditEntry: {
            id: number;
            action: components["schemas"]["ActionEnum"];
            /** Format: date-time */
            created_at: string;
            actor: components["schemas"]["UserReference"] | null;
            target: components["schemas"]["UserReference"] | null;
        };
        CsrfToken: {
            csrfToken: string;
        };
        DeactivationImpact: {
            future_reservations: number;
        };
        DeactivationRequest: {
            /** @default false */
            confirm: boolean;
        };
        DeactivationResult: {
            deactivated: boolean;
            impact: components["schemas"]["DeactivationImpact"];
            user: components["schemas"]["AdminUser"];
        };
        Health: {
            status: string;
            database: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        PaginatedAdminUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminUser"][];
        };
        PatchedUserUpdate: {
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            is_active?: boolean;
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
        };
        RoleAssignment: {
            roles: components["schemas"]["RolesEnum"][];
        };
        RoleCounts: {
            STUDENT: number;
            MONITOR: number;
            TEACHER: number;
            ADMIN: number;
        };
        /**
         * @description * `STUDENT` - Estudiante
         *     * `MONITOR` - Monitor
         *     * `TEACHER` - Docente
         *     * `ADMIN` - Administrador
         * @enum {string}
         */
        RolesEnum: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Correo
             * Format: email
             */
            readonly email: string;
            /** Nombre */
            readonly first_name: string;
            /** Apellido */
            readonly last_name: string;
            readonly roles: components["schemas"]["RolesEnum"][];
        };
        /** @description Same rules as self-registration, but the administrator chooses the roles. */
        UserCreate: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
            roles: components["schemas"]["RolesEnum"][];
        };
        UserReference: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            readonly full_name: string;
        };
        UserSummary: {
            total: number;
            active: number;
            inactive: number;
            joined_last_30_days: number;
            by_role: components["schemas"]["RoleCounts"];
            recent_activity: components["schemas"]["AuditEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /**
                 * @description * `STUDENT` - Estudiante
                 *     * `MONITOR` - Monitor
                 *     * `TEACHER` - Docente
                 *     * `ADMIN` - Administrador
                 */
                role?: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
                /** @description Busca en correo, nombres, apellidos y nombre completo. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreate"];
                "multipart/form-data": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_deactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeactivationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DeactivationRequest"];
                "multipart/form-data": components["schemas"]["DeactivationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeactivationResult"];
                };
            };
        };
    };
    users_roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignment"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleAssignment"];
                "multipart/form-data": components["schemas"]["RoleAssignment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    users_export_retrieve: {
        parameters: {
            query?: {
                is_active?: boolean;
                /**
                 * @description * `STUDENT` - Estudiante
                 *     * `MONITOR` - Monitor
                 *     * `TEACHER` - Docente
                 *     * `ADMIN` - Administrador
                 */
                role?: "STUDENT" | "MONITOR" | "TEACHER" | "ADMIN";
                /** @description Busca en correo, nombres, apellidos y nombre completo. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excel workbook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
}
